name: RefreshVersions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'

jobs:
  "Refresh-Versions":
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - id: step-0
        name: check-out
        uses: actions/checkout@v3
        with:
          ref: develop

      - id: step-1
        name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - id: step-2
        name: create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: dependency-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: step-3
        name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions

      - id: step-4
        name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: Refresh versions.properties
          new_branch: dependency-update
          push: --force --set-upstream origin dependency-update

      - id: step-5
        name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dependency-update
          destination_branch: develop
          pr_title: Upgrade Gradle dependencies
          pr_body: '[refreshVersions](https://github.com/jmfayard/refreshVersions) has found these library updates!'
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}